apiVersion: v1
kind: Service
metadata:
  name: welder
spec:
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 8080
    protocol: TCP
    name: welder-port
  - nodePort: 30001
    port: 8888
    targetPort: 8888
    protocol: TCP
    name: jupyter-port
  selector:
    app: welder
  type: NodePort
  # # Static IP created using `gcloud compute addresses create ccm-external-ip --region us-central1`
  # loadBalancerIP: "127.0.0.1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: welder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: welder
    spec:
      containers:
      - name: welder
        env:
          - name: OWNER_EMAIL
            value: fake@gmail.com
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/docker/.config/gcloud/application_default_credentials.json
        image: us.gcr.io/broad-dsp-gcr-public/welder-server:latest
        ports:
          - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/docker/.config
          name: application-default-credential
        - mountPath: /opt/docker/work
          name: shared
      - name: jupyter
        image: jupyter/minimal-notebook:latest
        env:
          - name: OWNER_EMAIL
            value: fake@gmail.com
          - name: CLUSTER_NAME
            value: local-cluster
          - name: WORKSPACE_NAMESPACE
            value: broad-dsde-dev
          - name: GOOGLE_PROJECT
            value: broad-dsde-dev
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/docker/.config/gcloud/application_default_credentials.json
        ports:
          - containerPort: 8888
        volumeMounts:
          - mountPath: /opt/docker/.config
            name: application-default-credential
          - mountPath: /work
            name: shared
      volumes:
      - name: application-default-credential
        hostPath:
          path: /Users/qi/.config
          type: Directory
      - name: shared
        emptyDir: {}